### ISSUE TITLE
VoxelStatsShowOnTemplate.m: change "mean" to "nanmean" in line 21:23

### ISSUE THREAD

**Issue by rullator** [sulantha2006/VoxelStats#3]
I ran into problems while visualizing the tmaps. After modeling the data, I had voxels containing "NaN". When computing the glassbrain projection with "mean" die projection get values of "NaN". Later you set the clim according to max value of the average slice, which also get set to NaN then. THis throws an error.
If you change the "mean" to "nanmean", this issue can be fixed.

Best
Michael

**Comment by sulantha2006** [comment]
Thanks a lot. I will add the modifications.

**Comment by sulantha2006** [comment]
Resolved in the latest commit. Thanks again.
