### ISSUE TITLE
Mask read fail 

### ISSUE THREAD

**Issue by dsodums** [sulantha2006/VoxelStats#4]
I tried running a linear model using the GUI method and keep getting errors saying it can't read the mask I have supplied.  I have used the "mni_icbm152_t1_tal_nlin_sym_09c_mask.mnc" minc file that has always worked for me when running linear models in RMINC so I'm confused why it is having problems reading the file.  I checked the dimensions and they are the same as the preprocessed VBM files I have supplied with a .csv file.  Both my input files and the mask are minc V2 files.  

Any thoughts?
![voxelstats_exampleguisetup](https://cloud.githubusercontent.com/assets/13490288/19400194/1317fe98-9223-11e6-9a28-0b62443fd149.png)

I have attached a screenshot of the GUI setup and my CSV file, and here is the error message from Matlab 2015a:

In readMaskSlices (line 5)
            [mask_slices_n, mask_height, mask_width, mask_slices, voxel_dims,
            slices_data] = getMaskSlicesMinc(maskFile);

In VoxelStatsLM (line 31)
    [slices, image_height, image_width, mask_slices, voxel_dims, slices_data] =
    readMaskSlices(imageType, mask_file);

In runVS (line 21)
                [ c_struct, slices_p, image_height_p, image_width_p, coeff_vars,
                voxel_num, df, voxel_dims]  = ...

![voxelstats_exampleguisetup](https://cloud.githubusercontent.com/assets/13490288/19400205/214facc2-9223-11e6-923f-5969c3bcd9bf.png)

**Comment by sulantha2006** [comment]
This can be an issue with emma tools not correctly installed. 
Can you use emma tools to read minc files. 
Try this command: 

`mask = openimage(mask_file);`
`mask_slices_n = getimageinfo(mask, 'NumSlices');`
`mask_file` - file path for the mask file. 

Let me know if this works.

**Comment by ykjymkoko** [comment]
Supplementary information:
I have the same error messages when using a nifti mask file.
The problem was resolved after setting the path for VoxelStats with all subfolders in Matlab.
